In [1]:
import pandas as pd
import os 
current_dir = os.getcwd()
import shutil
folder = os.path.join(current_dir, "selected_data")
if os.path.isdir(folder):
    shutil.rmtree(folder)
    os.mkdir(folder)

In [2]:
train = pd.read_csv("Dataset\\train.tsv", sep='\t', names=['id', 'label', 'statement', 'subject(s)', 'speaker', 'speaker\'s job title', 'state info', 'party affiliation', 'credit history count', 'true count', 'false count', 'half true count', 'most true count', 'pants on fire count', 'context'], header=None)

In [3]:
train.head()

,id,label,statement,subject(s),speaker,speaker's job title,state info,party affiliation,credit history count,true count,false count,half true count,most true count,pants on fire count,context
0,2635.json,false,Says the Annies List political group supports ...,abortion,dwayne-bohac,State representative,Texas,republican,0.0,1.0,0.0,0.0,0.0,a mailer,NaN
1,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.,NaN
2,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver,NaN
3,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release,NaN
4,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN,NaN

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10240 entries, 0 to 10239
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10240 non-null  object
 1   label                 10240 non-null  object
 2   statement             10240 non-null  object
 3   subject(s)            10238 non-null  object
 4   speaker               10238 non-null  object
 5   speaker's job title   7343 non-null   object
 6   state info            8032 non-null   object
 7   party affiliation     10238 non-null  object
 8   credit history count  10238 non-null  float64
 9   true count            10238 non-null  float64
 10  false count           10238 non-null  float64
 11  half true count       10238 non-null  float64
 12  most true count       10238 non-null  float64
 13  pants on fire count   10138 non-null  object
 14  context               0 non-null      float64
dtypes: float64(6), object(9)
memory usage: 1.2+ MB

In [5]:
train = train[['label', 'statement']]

In [6]:
train.head()

         label                                          statement
0        false  Says the Annies List political group supports ...
1    half-true  When did the decline of coal start? It started...
2  mostly-true  Hillary Clinton agrees with John McCain "by vo...
3        false  Health care reform legislation is likely to ma...
4    half-true  The economic turnaround started at the end of ...

In [7]:
train.to_csv(os.path.join(folder, 'train.csv'), index=False)

In [8]:
test = pd.read_csv("Dataset\\test.tsv", sep='\t', names=['id', 'label', 'statement', 'subject(s)', 'speaker', 'speaker\'s job title', 'state info', 'party affiliation', 'credit history count', 'true count', 'false count', 'half true count', 'most true count', 'pants on fire count', 'context'], header=None)

In [9]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1267 entries, 0 to 1266
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1267 non-null   object
 1   label                 1267 non-null   object
 2   statement             1267 non-null   object
 3   subject(s)            1267 non-null   object
 4   speaker               1267 non-null   object
 5   speaker's job title   942 non-null    object
 6   state info            1005 non-null   object
 7   party affiliation     1267 non-null   object
 8   credit history count  1267 non-null   int64
 9   true count            1267 non-null   int64
 10  false count           1267 non-null   int64
 11  half true count       1267 non-null   int64
 12  most true count       1267 non-null   int64
 13  pants on fire count   1250 non-null   object
 14  context               0 non-null      float64
dtypes: float64(1), int64(5), object(9)
memory usage: 148.6+ KB

In [10]:
test.head()

,id,label,statement,subject(s),speaker,speaker's job title,state info,party affiliation,credit history count,true count,false count,half true count,most true count,pants on fire count,context
0,11972.json,true,Building a wall on the U.S.-Mexico border will...,immigration,rick-perry,Governor,Texas,republican,30,30,42,23,18,Radio interview,NaN
1,11685.json,false,Wisconsin is on pace to double the number of l...,jobs,katrina-shankland,State representative,Wisconsin,democrat,2,1,0,0,0,a news conference,NaN
2,11096.json,false,Says John McCain has done nothing to help the ...,"military,veterans,voting-record",donald-trump,President-Elect,New York,republican,63,114,51,37,61,comments on ABC's This Week.,NaN
3,5209.json,half-true,Suzanne Bonamici supports a plan that will cut...,"medicare,message-machine-2012,campaign-adverti...",rob-cornilles,consultant,Oregon,republican,1,1,3,1,1,a radio show,NaN
4,9524.json,pants-fire,When asked by a reporter whether hes at the ce...,"campaign-finance,legal-issues,campaign-adverti...",state-democratic-party-wisconsin,NaN,Wisconsin,democrat,5,7,2,2,7,a web video,NaN

In [11]:
test = test[['label', 'statement']]

In [12]:
test.to_csv(os.path.join(folder, 'test.csv'), index=False)

In [13]:
valid = pd.read_csv("Dataset\\valid.tsv", sep='\t', names=['id', 'label', 'statement', 'subject(s)', 'speaker', 'speaker\'s job title', 'state info', 'party affiliation', 'credit history count', 'true count', 'false count', 'half true count', 'most true count', 'pants on fire count', 'context'], header=None)

In [14]:
valid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1284 entries, 0 to 1283
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1284 non-null   object
 1   label                 1284 non-null   object
 2   statement             1284 non-null   object
 3   subject(s)            1284 non-null   object
 4   speaker               1284 non-null   object
 5   speaker's job title   939 non-null    object
 6   state info            1005 non-null   object
 7   party affiliation     1284 non-null   object
 8   credit history count  1284 non-null   int64
 9   true count            1284 non-null   int64
 10  false count           1284 non-null   int64
 11  half true count       1284 non-null   int64
 12  most true count       1284 non-null   int64
 13  pants on fire count   1272 non-null   object
 14  context               0 non-null      float64
dtypes: float64(1), int64(5), object(9)
memory usage: 150.6+ KB

In [15]:
valid = valid[['label', 'statement']]

In [16]:
valid.to_csv(os.path.join(folder, 'valid.csv'), index=False)